BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
USE [EMaaS]
GO
ALTER TABLE [Information].[Date] 
ADD WeekId BIGINT NOT NULL
GO
ALTER TABLE [Information].[Date] ADD CONSTRAINT
	FK_Date_WeekId FOREIGN KEY
	(
	WeekId
	) REFERENCES [Information].[Week]
	(
	WeekId
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION
GO
DECLARE @v sql_variant 
SET @v = N'Foreign Key constraint joining [Information].[Date].WeekId to [Information].[Week].WeekId'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'Information', N'TABLE', N'Date', N'CONSTRAINT', N'FK_Date_WeekId'
GO
COMMIT
