USE [master]
GO

IF NOT EXISTS(SELECT TOP 1 1 FROM syslogins WHERE loginname = 'CommitBasketData.api')
    BEGIN
       CREATE LOGIN [CommitBasketData.api] WITH PASSWORD=N'zkNYKFH6sdsPPXqz', DEFAULT_DATABASE=[EMaaS], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
    END
GO
