USE [master]
GO

IF NOT EXISTS(SELECT TOP 1 1 FROM syslogins WHERE loginname = 'Website.api')
    BEGIN
        CREATE LOGIN [Website.api] WITH PASSWORD=N'xwUR74sRX3SqSHKq', DEFAULT_DATABASE=[EMaaS], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
    END
GO