USE [master]
GO

IF NOT EXISTS(SELECT TOP 1 1 FROM syslogins WHERE loginname = 'CreateDateForecastApp')
    BEGIN
       CREATE LOGIN [CreateDateForecastApp] WITH PASSWORD=N'YLtRVcMGf7UUALXU', DEFAULT_DATABASE=[EMaaS], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
    END
GO
