USE [master]
GO

IF NOT EXISTS(SELECT TOP 1 1 FROM syslogins WHERE loginname = 'CommitSubMeterData.api')
    BEGIN
       CREATE LOGIN [CommitSubMeterData.api] WITH PASSWORD=N'nZYGJvSe4Ej3dzFH', DEFAULT_DATABASE=[EMaaS], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
    END
GO
