USE [master]
GO

IF NOT EXISTS(SELECT TOP 1 1 FROM syslogins WHERE loginname = 'CommitMeterData.api')
    BEGIN
       CREATE LOGIN [CommitMeterData.api] WITH PASSWORD=N'jC7jNZZnz63nNysc', DEFAULT_DATABASE=[EMaaS], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
    END
GO
