USE [EMaaS]
GO

DECLARE @CreatedByUserId BIGINT = (SELECT UserId FROM [Administration.User].[User] WHERE UserGUID = '743E21EE-2185-45D4-9003-E35060B751E2')
DECLARE @SourceAttributeId BIGINT = (SELECT SourceAttributeId FROM [Information].[SourceAttribute] WHERE SourceAttributeDescription = 'User Generated')
DECLARE @SourceId BIGINT = (SELECT SourceId FROM [Information].[SourceDetail] WHERE SourceAttributeId = @SourceAttributeId AND SourceDetailDescription = @CreatedByUserId)

EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'CustomerName'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'ContactName'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'ContactRole'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'ContactTelephoneNumber'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'ContactEmailAddress'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'MPXN'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'GridSupplyPoint'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'ProfileClass'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'MeterTimeswitchCode'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'LineLossFactorClass'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'LocalDistributionZone'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'Capacity'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'StandardOfftakeQuantity'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'AnnualUsage'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'ImportExport'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'MeterSerialNumber'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'Area'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'SiteName'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'SiteAddress'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'SiteTown'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'SiteCounty'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'SitePostCode'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'SiteDescription'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'SubMeterIdentifier'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'SerialNumber'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'SubArea'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'Asset'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'ExemptionProduct'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'ExemptionProportion'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'Date'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'DateFrom'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'DateTo'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'TimePeriod'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'ContractReference'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'Supplier'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'ContractStartDate'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'ContractEndDate'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'Product'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'RateCount'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'StandingCharge'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'CapacityCharge'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'Rate'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'Value'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'BasketReference'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'RateType'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'Volume'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'TradeReference'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'TradeDate'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'TradeProduct'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'Price'
EXEC [Customer].[DataUploadValidationErrorEntityAttribute_Insert] @CreatedByUserId, @SourceId, 'Direction'