USE [EMaaS]
GO

GRANT EXECUTE ON OBJECT::[Mapping].[ContractToMeterToContractMeterToProductToContractMeterRateToRateType_GetByContractToMeterToContractMeterToProductIdAndContractMeterRateToRateTypeId] TO [CommitContractData.api];
GO