USE [master]
GO

IF NOT EXISTS(SELECT TOP 1 1 FROM syslogins WHERE loginname = 'GetMappedUsageDateIdApp')
    BEGIN
       CREATE LOGIN [GetMappedUsageDateIdApp] WITH PASSWORD=N'exW3hgGLhw8P3Gka', DEFAULT_DATABASE=[EMaaS], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
    END
GO
