USE [EMaaS]
GO

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
IF  EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[Temp.CustomerDataUpload].[MeterUsage]') AND type in (N'U'))
DROP TABLE [Temp.CustomerDataUpload].[MeterUsage]
GO
CREATE TABLE [Temp.CustomerDataUpload].[MeterUsage]
	(
	ProcessQueueGUID UNIQUEIDENTIFIER,
	SheetName VARCHAR(255),
	RowId INT,
	MPXN VARCHAR(255),
	Date VARCHAR(255),
	TimePeriod VARCHAR(255),
	Value VARCHAR(255),
	CanCommit BIT
	)  ON [Temp]
GO
ALTER TABLE [Temp.CustomerDataUpload].[MeterUsage] ADD CONSTRAINT
	DF_MeterUsage_CanCommit DEFAULT 0 FOR CanCommit
GO
ALTER TABLE [Temp.CustomerDataUpload].[MeterUsage] SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
