USE [master]
GO

IF NOT EXISTS(SELECT TOP 1 1 FROM syslogins WHERE loginname = 'CreateMonthForecastApp')
    BEGIN
       CREATE LOGIN [CreateMonthForecastApp] WITH PASSWORD=N'9JQtHgkA2CcnaE67', DEFAULT_DATABASE=[EMaaS], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
    END
GO
