USE [EMaaS]
GO

DECLARE @CreatedByUserId BIGINT = (SELECT UserId FROM [Administration.User].[User] WHERE UserGUID = '743E21EE-2185-45D4-9003-E35060B751E2')
DECLARE @SourceAttributeId BIGINT = (SELECT SourceAttributeId FROM [Information].[SourceAttribute] WHERE SourceAttributeDescription = 'User Generated')
DECLARE @SourceId BIGINT = (SELECT SourceId FROM [Information].[SourceDetail] WHERE SourceAttributeId = @SourceAttributeId AND SourceDetailDescription = @CreatedByUserId)

EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 1'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 2'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 3'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 4'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 5'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 6'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 7'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 8'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 9'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 10'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 11'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 12'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 13'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 14'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 15'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 16'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 17'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 18'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 19'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 20'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 21'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 22'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 23'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 24'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 25'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 26'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 27'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 28'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 29'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 30'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 31'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 32'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 33'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 34'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 35'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 36'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 37'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 38'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 39'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 40'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 41'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 42'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 43'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 44'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 45'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 46'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 47'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 48'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 49'
EXEC [Information].[HalfHour_Insert] @CreatedByUserId, @SourceId, 'Half Hour 50'