USE [master]
GO

IF NOT EXISTS(SELECT TOP 1 1 FROM syslogins WHERE loginname = 'ValidatePageGUID.api')
    BEGIN
        CREATE LOGIN [ValidatePageGUID.api] WITH PASSWORD=N'n:Q>V&6P9KtG`(5k', DEFAULT_DATABASE=[EMaaS], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
    END
GO