USE [master]
GO

IF NOT EXISTS(SELECT TOP 1 1 FROM syslogins WHERE loginname = 'GetProfileId.api')
    BEGIN
       CREATE LOGIN [GetProfileId.api] WITH PASSWORD=N'cJRxAJC7xnsP5PBF', DEFAULT_DATABASE=[EMaaS], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
    END
GO
