USE [master]
GO

IF NOT EXISTS(SELECT TOP 1 1 FROM syslogins WHERE loginname = 'CommitMeterToSubMeterDataApp')
    BEGIN
       CREATE LOGIN [CommitMeterToSubMeterDataApp] WITH PASSWORD=N'g89M9Px2AtzgJ3N2', DEFAULT_DATABASE=[EMaaS], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
    END
GO
