USE [master]
GO

IF NOT EXISTS(SELECT TOP 1 1 FROM syslogins WHERE loginname = 'CommitSiteDataApp')
    BEGIN
       CREATE LOGIN [CommitSiteDataApp] WITH PASSWORD=N'vZ3RFaCBjSLCbFwc', DEFAULT_DATABASE=[EMaaS], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
    END
GO
