USE [master]
GO

IF NOT EXISTS(SELECT TOP 1 1 FROM syslogins WHERE loginname = 'GetGenericProfileApp')
    BEGIN
       CREATE LOGIN [GetGenericProfileApp] WITH PASSWORD=N'ukNWrT725QtL796V', DEFAULT_DATABASE=[EMaaS], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
    END
GO
