USE [EMaaS]
GO

DECLARE @CreatedByUserId BIGINT = (SELECT UserId FROM [Administration.User].[User] WHERE UserGUID = '743E21EE-2185-45D4-9003-E35060B751E2')
DECLARE @SourceAttributeId BIGINT = (SELECT SourceAttributeId FROM [Information].[SourceAttribute] WHERE SourceAttributeDescription = 'User Generated')
DECLARE @SourceId BIGINT = (SELECT SourceId FROM [Information].[SourceDetail] WHERE SourceAttributeId = @SourceAttributeId AND SourceDetailDescription = @CreatedByUserId)

EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 1'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 2'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 3'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 4'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 5'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 6'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 7'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 8'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 9'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 10'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 11'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 12'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 13'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 14'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 15'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 16'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 17'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 18'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 19'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 20'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 21'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 22'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 23'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 24'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 25'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 26'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 27'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 28'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 29'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 30'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 31'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 32'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 33'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 34'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 35'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 36'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 37'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 38'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 39'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 40'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 41'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 42'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 43'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 44'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 45'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 46'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 47'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 48'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 49'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 50'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 51'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 52'
EXEC [Information].[Week_Insert] @CreatedByUserId, @SourceId, 'Week 53'