USE [master]
GO

IF NOT EXISTS(SELECT TOP 1 1 FROM syslogins WHERE loginname = 'CommitMeterDataApp')
    BEGIN
       CREATE LOGIN [CommitMeterDataApp] WITH PASSWORD=N'jC7jNZZnz63nNysc', DEFAULT_DATABASE=[EMaaS], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
    END
GO
