USE [master]
GO

IF NOT EXISTS(SELECT TOP 1 1 FROM syslogins WHERE loginname = 'CommitFlexTradeData.api')
    BEGIN
       CREATE LOGIN [CommitFlexTradeData.api] WITH PASSWORD=N'3HXnZHc5GpUhzEA9', DEFAULT_DATABASE=[EMaaS], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
    END
GO
