USE [master]
GO

IF NOT EXISTS(SELECT TOP 1 1 FROM syslogins WHERE loginname = 'CommitBasketDataApp')
    BEGIN
       CREATE LOGIN [CommitBasketDataApp] WITH PASSWORD=N'zkNYKFH6sdsPPXqz', DEFAULT_DATABASE=[EMaaS], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
    END
GO
