USE [EMaaS]
GO

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
IF  EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[Temp.Customer].[Site]') AND type in (N'U'))
DROP TABLE [Temp.Customer].[Site]
GO
CREATE TABLE [Temp.Customer].[Site]
	(
	ProcessQueueGUID UNIQUEIDENTIFIER,
	SiteName VARCHAR(255),
	SiteAddress VARCHAR(255),
	SiteTown VARCHAR(255),
	SiteCounty VARCHAR(255),
	SitePostCode VARCHAR(255)
	)  ON [Temp]
GO
ALTER TABLE [Temp.Customer].[Site] SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
