USE [EMaaS]
GO

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
IF  EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'[Temp.CustomerDataUpload].[SubMeter]') AND type in (N'U'))
DROP TABLE [Temp.CustomerDataUpload].[SubMeter]
GO
CREATE TABLE [Temp.CustomerDataUpload].[SubMeter]
	(
	ProcessQueueGUID UNIQUEIDENTIFIER,
	RowId INT,
	MPXN VARCHAR(255),
	SubMeterIdentifier VARCHAR(255),
	SerialNumber VARCHAR(255),
	SubArea VARCHAR(255),
	Asset VARCHAR(255),
	CanCommit BIT
	)  ON [Temp]
GO
ALTER TABLE [Temp.CustomerDataUpload].[SubMeter] ADD CONSTRAINT
	DF_Site_CanCommit DEFAULT 0 FOR CanCommit
GO
ALTER TABLE [Temp.CustomerDataUpload].[SubMeter] SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
