USE [master]
GO

IF NOT EXISTS(SELECT TOP 1 1 FROM syslogins WHERE loginname = 'CommitSiteData.api')
    BEGIN
       CREATE LOGIN [CommitSiteData.api] WITH PASSWORD=N'vZ3RFaCBjSLCbFwc', DEFAULT_DATABASE=[EMaaS], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
    END
GO
