USE [master]
GO

/****** Object:  Database [EMaaS]    Script Date: 05/05/2020 08:28:12 ******/
EXEC msdb.dbo.sp_delete_database_backuphistory @database_name = N'EMaaS'
GO
USE [master]
GO
/****** Object:  Database [EMaaS]    Script Date: 05/05/2020 08:33:02 ******/
IF EXISTS(SELECT TOP 1 1 FROM sys.databases where name = 'EMaas')
	BEGIN
		ALTER DATABASE [EMaaS] SET  SINGLE_USER WITH ROLLBACK IMMEDIATE
		DROP DATABASE [EMaaS]
	END
GO

/****** Object:  Database [EMaaS]    Script Date: 05/05/2020 08:28:12 ******/
DECLARE @DataPath AS NVARCHAR(255) = (SELECT CONVERT(NVARCHAR(255), SERVERPROPERTY ('InstanceDefaultDataPath')))
DECLARE @LogPath AS NVARCHAR(255) = (SELECT CONVERT(NVARCHAR(255), SERVERPROPERTY ('InstanceDefaultLogPath')))
DECLARE @SQL NVARCHAR(500) = '
CREATE DATABASE [EMaaS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N''EMaaS'', FILENAME = N''' + @DataPath + 'EMaaS.mdf'' , SIZE = 10240KB , MAXSIZE = UNLIMITED, FILEGROWTH = 5%)
 LOG ON 
( NAME = N''EMaaS_log'', FILENAME = N''' + @LogPath + 'EMaaS_log.ldf'' , SIZE = 10240KB , MAXSIZE = UNLIMITED , FILEGROWTH = 10%)'

EXEC sp_sqlexec @SQL

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EMaaS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EMaaS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EMaaS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EMaaS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EMaaS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EMaaS] SET ARITHABORT OFF 
GO

ALTER DATABASE [EMaaS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EMaaS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EMaaS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EMaaS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EMaaS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EMaaS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EMaaS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EMaaS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EMaaS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EMaaS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [EMaaS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EMaaS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EMaaS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EMaaS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EMaaS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EMaaS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EMaaS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EMaaS] SET RECOVERY FULL 
GO

ALTER DATABASE [EMaaS] SET  MULTI_USER 
GO

ALTER DATABASE [EMaaS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EMaaS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EMaaS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EMaaS] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [EMaaS] SET QUERY_STORE = ON (OPERATION_MODE = READ_WRITE);
GO

ALTER DATABASE [EMaaS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [EMaaS] SET  READ_WRITE 
GO